import{a as g,S as b,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const L="49659545-2259a1a5c522b42738e4f2b2d",w="https://pixabay.com/api/";async function d(s,o){return(await g.get(w,{params:{key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),S=new b(".gallery a");function u(s){const o=s.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img class="images" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p><b>Likes:</b><br> ${r.likes}</p>
        <p><b>Views:</b><br>${r.views}</p>
        <p><b>Comments:</b><br> ${r.comments}</p>
        <p><b>Downloads:</b><br> ${r.downloads}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",o),S.refresh()}function v(){h.innerHTML=""}function m(){p.classList.remove("hidden")}function l(){p.classList.add("hidden")}function f(){y.classList.remove("hidden")}function c(){y.classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".form");let o="",r=1,a=0;s.addEventListener("submit",async e=>{if(e.preventDefault(),o=e.target.elements.SearchText.value.trim(),!o){n.warning({message:"Please enter a search term"});return}v(),c(),m();try{const t=await d(o,r);if(t.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query."});return}u(t.hits),a=Math.ceil(t.totalHits/15),a>1&&f()}catch{l(),n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{l()}}),document.querySelector(".load-more").addEventListener("click",async()=>{r++,m(),c();try{const e=await d(o,r);u(e.hits),r>=a?(c(),n.info({message:"End of search results"})):f();const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2.5,behavior:"smooth"})}catch{n.error({message:"Failed to load more images"})}finally{l()}})});
//# sourceMappingURL=index.js.map
